name:                da-loute-bot
version:             0.1.0.0
github:              "pengstrom/da-loute-bot"
license:             BSD3
author:              "Per Engström"
maintainer:          "per.olov.engstrom@gmail.com"
copyright:           "2018 Per Engström"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/pengstrom/da-loute-bot#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec

library:
  source-dirs: src

executables:
  da-loute-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - da-loute-bot

tests:
  da-loute-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - da-loute-bot
    - QuickCheck
